# Generated by Django 6.0 on 2026-01-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('cash', 'cash'), ('cart', 'cart'), ('both', 'both')])),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.IntegerField()),
                ('orders_count', models.IntegerField(default=0)),
                ('working_status', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery_addresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_name', models.TextField(max_length=500)),
                ('langitude', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField()),
                ('group_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery_group_topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=255)),
                ('message_id', models.IntegerField()),
                ('topic_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Delivery_wallet_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cash', models.IntegerField(default=0)),
                ('amount_cart', models.IntegerField(default=0)),
                ('is_take', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery_workdays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Week_days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
