# Generated by Django 6.0 on 2026-01-05 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delivery_addresses',
            name='delivery_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.delivery'),
        ),
        migrations.AddField(
            model_name='delivery_group',
            name='delivery_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.delivery'),
        ),
        migrations.AddField(
            model_name='delivery_group_topic',
            name='delivery_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.delivery_group'),
        ),
        migrations.AddField(
            model_name='delivery_wallet_log',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.delivery'),
        ),
        migrations.AddField(
            model_name='delivery_wallet_log',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.ask'),
        ),
        migrations.AddField(
            model_name='delivery_wallet_log',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delivery_workdays',
            name='delivery_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.delivery'),
        ),
        migrations.AddField(
            model_name='delivery_workdays',
            name='week_days',
            field=models.ManyToManyField(blank=True, null=True, to='delivery.week_days'),
        ),
    ]
