# Generated by Django 6.0 on 2026-01-05 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='celler',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='celler_wallet_log',
            name='celler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.celler'),
        ),
        migrations.AddField(
            model_name='kombo_products',
            name='kombo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.kombo_products'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='celler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.celler'),
        ),
        migrations.AddField(
            model_name='kombo_products',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.product'),
        ),
    ]
